export const initialEmptyValues = {
  personalInfo: {
    dob: "",
    profilePic: "",
    occupation: "",
    nickName: "",
  },
  contactInfo: {
    countryCode: "+91",
    mobileNumber: "",
    whatsappNumber: "",
    homeAddress: "",
    officeAddress: "",
  },
  socialMedia: {
    instagramId: "",
    facebookId: "",
    youtubeLink: "",
  },
  vehicleInfo: [
    {
      make: "",
      model: "",
      registrationNumber: "",
    },
  ],
  longestRideExperience: "",
  ridingGroupMember: "no",
  DLInfo: {
    DLNumber: "",
    DLIssuedAt: "",
    DLValidUpTo: "",
    DLFile: "",
  },
  emergencyContactInfo: {
    emergencyContactNameInFamily: "",
    emergencyContactNumberInFamily: "",
    emergencyContactRelationship: "",
    emergencyContactNameInBangalore: "",
    emergencyContactNumberInBangalore: "",
    emergencyContactNameInBMR: "",
    location: "",
  },
  medicalInfo: {
    bloodGroup: "O +ve",
    alergies: "",
    preExistingMedicalCondition: "",
    climateSensitivities: "",
    medicationRequirements: "",
  },
  insuranceInfo: {
    company: "",
    number: "",
    validity: "",
  },
  otherInfo: {
    nativeInKerala: "",
    area: "",
    volunteerPreference: "yes",
    specialNote: "",
  },
  ack1: true,
  ack2: true,
  ack3: true,
  agreeToRules: true,
};
